language: node_js

sudo: false

notifications:
  email: false

node_js:
  - 11.8.0

cache:
  directories:
    - node_modules

branches:
  only:
    - source

before_install:
  - npm install -g hexo-cli

install:
  - yarn

script:
  - hexo clean
  - hexo generate

after_script:
  - git config --global user.name "tinyalley"
  - git config --global user.email "alley.ma@qq.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy
